import http from 'node:http';
import { readFile, mkdir } from 'node:fs/promises';
import { extname, resolve } from 'node:path';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium: pw } = require(process.env.STUDY_PLAYWRIGHT_MODULE || 'playwright');
const root = new URL('../dist/', import.meta.url).pathname.replace(/\/$/, '');
const output = new URL('../test-results/', import.meta.url).pathname; await mkdir(output, { recursive: true });
const mime = { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html', '.svg': 'image/svg+xml', '.webmanifest': 'application/manifest+json' };
const server = http.createServer(async (req, res) => {
  const file = resolve(root, '.' + new URL(req.url, 'http://localhost').pathname.replace(/\/$/, '/index.html'));
  if (!file.startsWith(root + '/')) { res.writeHead(403); res.end(); return; }
  try { const bytes = await readFile(file); res.writeHead(200, { 'Content-Type': mime[extname(file)] || 'application/octet-stream' }); res.end(bytes); }
  catch { res.writeHead(404); res.end(); }
});
await new Promise(done => server.listen(3123, '127.0.0.1', done));
const url = 'http://127.0.0.1:3123';
const browser = await pw.launch({ ...(process.env.STUDY_CHROMIUM_EXECUTABLE ? { executablePath: process.env.STUDY_CHROMIUM_EXECUTABLE } : {}), headless: true });
const errors = [], external = [];
const ctx = await browser.newContext({ viewport: { width: 1360, height: 1060 }, acceptDownloads: true, colorScheme: 'dark' });
const page = await ctx.newPage();
page.on('pageerror', e => errors.push(e.message));
page.on('request', req => { if (!req.url().startsWith(url)) external.push(req.url()); });
const getData = p => p.evaluate(() => new Promise((resolve, reject) => {
  const r = indexedDB.open('closet-prayer-study', 1); r.onsuccess = () => { const q = r.result.transaction('state').objectStore('state').get('notebook'); q.onsuccess = () => resolve(q.result); q.onerror = reject; }; r.onerror = reject;
}));
const waitSaved = async p => {
  await p.waitForFunction(() => document.querySelector('.save-indicator')?.textContent === 'Saved on this device');
};
const say = text => console.log(text);
try {
  await page.goto(url); await page.getByRole('heading', { name: 'What are you wondering about?' }).waitFor();
  await page.screenshot({ path: output + '/01-explore-desktop-dark.png', fullPage: true });
  await page.getByRole('button', { name: 'Use light mode' }).click();
  await page.screenshot({ path: output + '/02-explore-desktop-light.png', fullPage: true });
  for (const width of [344, 390, 768]) {
    await page.setViewportSize({ width, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Home overflow at ${width}`);
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: output + '/03-explore-mobile-light.png', fullPage: true });
  await page.getByRole('button', { name: 'Use dark mode' }).click();
  await page.screenshot({ path: output + '/04-explore-mobile-dark.png', fullPage: true });
  say('PASS: home, light/dark themes, and 344/390/768px overflow checks');

  await page.getByRole('searchbox', { name: 'Search a topic or question' }).fill('I saw my dead grandmother');
  await page.getByRole('button', { name: /What does the Bible say about those who have died/ }).click();
  await page.getByRole('heading', { name: 'What does the Bible say about those who have died?' }).waitFor();
  assert.equal(await page.locator('a[href*="biblegateway"]').count(), 0);
  await page.getByRole('button', { name: 'I need a Bible' }).click();
  assert.equal(await page.locator('a[href*="biblegateway"]').count(), 2);
  await page.getByLabel('Translation').selectOption('BSB');
  assert.match(await page.locator('a[href*="biblegateway"]').first().getAttribute('href'), /version=BSB/);
  await page.getByRole('button', { name: 'Use my own Bible' }).click();
  await page.locator('summary').filter({ hasText: 'Consider these passages together' }).click();
  await page.evaluate(() => window.scrollTo(0,0));
  await page.screenshot({ path: output + '/05-study-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Write a reflection', exact: true }).click();
  await page.getByLabel('My question or title').fill('What does death as sleep mean?');
  await page.getByLabel('My thoughts', { exact: true }).fill('I noticed that Jesus connects death with sleep. I am still considering what this means.');
  await page.locator('summary').filter({ hasText: 'Passages, topics' }).click();
  await page.getByLabel('My current understanding', { exact: true }).fill('My hope rests in resurrection.');
  await waitSaved(page);
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.reload();
  await page.getByRole('link', { name: 'My journal', exact: true }).click();
  await page.getByRole('button', { name: /Continue your draft/ }).click();
  assert.equal(await page.getByLabel('My question or title').inputValue(), 'What does death as sleep mean?');
  await page.getByRole('button', { name: 'Save reflection', exact: true }).click();
  await page.getByRole('button', { name: 'Reflect on this now' }).waitFor();
  await page.getByRole('button', { name: 'Correct wording' }).click();
  await page.getByLabel('My thoughts', { exact: true }).fill('Jesus describes Lazarus’s death as sleep. I am still considering what this means.');
  await page.getByRole('button', { name: 'Save correction' }).click();
  await page.locator('summary').filter({ hasText: 'Earlier wording' }).click();
  assert.ok((await page.locator('.revision').innerText()).includes('I noticed that Jesus'));
  await page.getByRole('button', { name: 'Reflect on this now' }).click();
  await page.getByLabel('My question or title').fill('Hope while I am grieving');
  await page.getByLabel('My thoughts', { exact: true }).fill('The promise of resurrection gives me room to grieve with hope.');
  await page.getByRole('button', { name: 'Save reflection', exact: true }).click();
  await waitSaved(page);
  let data = await getData(page);
  assert.equal(data.data.entries.length, 2);
  const original = data.data.entries.find(e => e.title.startsWith('What does'));
  const later = data.data.entries.find(e => e.title.startsWith('Hope'));
  assert.equal(original.revisions.length, 1); assert.equal(later.parentId, original.id);
  await page.getByRole('button', { name: 'All reflections' }).click();
  await page.getByRole('combobox', { name: 'Chronological order' }).selectOption('oldest');
  await page.screenshot({ path: output + '/06-journal-mobile.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  say('PASS: question matching, opt-in Bible links, draft reload, corrections, linked reflections');

  await page.getByRole('link', { name: 'Settings', exact: true }).click();
  const plainDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export full backup' }).click();
  await (await plainDownload).saveAs(output + '/plain-backup.json');
  const rawPlain = JSON.parse(await readFile(output + '/plain-backup.json', 'utf8'));
  assert.equal(rawPlain.data.entries.length, 2);
  const password = 'This is a test passphrase 123';
  await page.getByLabel('New passphrase', { exact: true }).fill(password);
  await page.getByLabel('Repeat passphrase', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Enable Private Vault' }).click();
  const recovery = await page.locator('.recovery-code').innerText();
  await page.getByRole('button', { name: 'I have saved my code' }).click();
  data = await getData(page);
  assert.equal(data.mode, 'vault'); assert.equal(data.data, undefined); assert.ok(!JSON.stringify(data).includes('Hope while I am grieving'));
  const encryptedDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export encrypted backup' }).click();
  await (await encryptedDownload).saveAs(output + '/encrypted-backup.json');
  assert.ok(!(await readFile(output + '/encrypted-backup.json', 'utf8')).includes('Hope while I am grieving'));
  await page.getByRole('button', { name: 'Lock now', exact: true }).click();
  await page.getByRole('heading', { name: 'Your notebook is locked' }).waitFor();
  await page.getByLabel('Passphrase', { exact: true }).fill('wrong password');
  await page.getByRole('button', { name: 'Unlock notebook' }).click();
  await page.getByText('That passphrase did not unlock the notebook.').waitFor();
  await page.getByRole('button', { name: 'Use my Recovery Code' }).click();
  await page.getByLabel('Recovery Code', { exact: true }).fill(recovery);
  await page.getByRole('button', { name: 'Unlock notebook' }).click();
  await page.getByRole('heading', { name: 'What are you wondering about?' }).waitFor();
  await page.reload(); await page.getByRole('heading', { name: 'Your notebook is locked' }).waitFor();
  await page.getByLabel('Passphrase', { exact: true }).fill(password); await page.getByRole('button', { name: 'Unlock notebook' }).click();
  await page.getByRole('heading', { name: 'What are you wondering about?' }).waitFor();
  await page.clock.install();
  await page.clock.fastForward(15 * 60 * 1000 + 16000);
  await page.getByRole('heading', { name: 'Your notebook is locked' }).waitFor();
  say('PASS: inactivity locks the encrypted notebook');
  say('PASS: encrypted local storage, encrypted export, wrong password, recovery unlock, reload lock');

  const importCtx = await browser.newContext({ viewport: { width: 390, height: 844 }, acceptDownloads: true });
  const ip = await importCtx.newPage(); ip.on('pageerror', e => errors.push(e.message));
  await ip.goto(url + '/#settings');
  await ip.getByLabel('Choose a Study backup', { exact: true }).setInputFiles(output + '/encrypted-backup.json');
  await ip.getByLabel('Backup passphrase', { exact: true }).fill(password);
  await ip.getByRole('button', { name: 'Open backup preview' }).click();
  await ip.getByRole('button', { name: 'Merge into my notebook' }).click();
  await ip.getByText(/Import complete: 2 entries added/).waitFor();
  assert.equal((await getData(ip)).data.entries.length, 2);
  await ip.getByLabel('Choose a Study backup', { exact: true }).setInputFiles(output + '/plain-backup.json');
  await ip.getByRole('button', { name: 'Merge into my notebook' }).click();
  await ip.getByText(/Import complete: 0 entries added/).waitFor();
  assert.equal((await getData(ip)).data.entries.length, 2);
  await ip.getByLabel('Choose a Study backup', { exact: true }).setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"wrong":true}') });
  await ip.getByText(/Choose a Closet Prayer Study backup/).waitFor();
  assert.equal((await getData(ip)).data.entries.length, 2);
  say('PASS: encrypted import into fresh browser, duplicate merge, malformed import leaves data intact');

  await ip.getByRole('link', { name: 'My journal', exact: true }).click();
  await ip.getByRole('button', { name: 'New reflection', exact: true }).click();
  await ip.getByLabel('My thoughts', { exact: true }).fill('Temporary entry to test explicit replacement.');
  await ip.getByRole('button', { name: 'Save reflection', exact: true }).click();
  await waitSaved(ip); assert.equal((await getData(ip)).data.entries.length, 3);
  await ip.getByRole('link', { name: 'Settings', exact: true }).click();
  await ip.getByLabel('Choose a Study backup', { exact: true }).setInputFiles(output + '/plain-backup.json');
  await ip.getByRole('button', { name: 'Replace from backup', exact: true }).click();
  assert.equal((await getData(ip)).data.entries.length, 3);
  await ip.getByRole('button', { name: 'Cancel', exact: true }).click();
  assert.equal((await getData(ip)).data.entries.length, 3);
  await ip.getByRole('button', { name: 'Replace from backup', exact: true }).click();
  await ip.getByRole('button', { name: 'Replace notebook', exact: true }).click();
  await ip.getByText('Full notebook restored.').waitFor();
  assert.equal((await getData(ip)).data.entries.length, 2);
  say('PASS: replace import only changes data after confirmation; cancel preserves it');

  await ip.evaluate(async () => { const reg = await navigator.serviceWorker.ready; if (!navigator.serviceWorker.controller) await new Promise(resolve => navigator.serviceWorker.addEventListener('controllerchange', resolve, { once: true })); });
  await importCtx.setOffline(true); await ip.reload();
  await ip.getByRole('heading', { name: 'Settings', exact: true }).waitFor();
  await ip.getByRole('link', { name: 'My journal', exact: true }).click();
  await ip.getByRole('heading', { name: 'Hope while I am grieving' }).waitFor();
  assert.equal((await getData(ip)).data.entries.length, 2);
  await importCtx.setOffline(false);
  await importCtx.close();
  say('PASS: offline reload retains app and journal');

  const raceCtx = await browser.newContext();
  const a = await raceCtx.newPage(), b = await raceCtx.newPage();
  await a.goto(url); await b.goto(url);
  await a.getByRole('button', { name: 'Write a reflection', exact: true }).click();
  await a.getByLabel('My thoughts', { exact: true }).fill('First tab work'); await waitSaved(a);
  await b.getByRole('button', { name: 'Write a reflection', exact: true }).click();
  await b.getByLabel('My thoughts', { exact: true }).fill('Second tab work');
  await b.getByText(/This notebook changed in another tab/).waitFor();
  assert.equal((await getData(b)).data.draft.body, 'First tab work');
  await raceCtx.close();
  say('PASS: stale tab cannot overwrite newer saved work');
  assert.deepEqual(errors, []); assert.deepEqual(external, []);
  say('PASS: no page errors or external requests during local study flows');
} catch (error) {
  await page.screenshot({ path: output + '/failure.png', fullPage: true }).catch(() => {});
  console.error(error); process.exitCode = 1;
} finally { await browser.close(); await new Promise(done => server.close(done)); }
